version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"   # FastAPI accessible depuis le r√©seau local
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: crm

  db:
    image: mariadb:11
    container_name: projet-web-db
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: crm
    ports:
      - "3310:3306"
    volumes:
      - ./db_data:/var/lib/mysql
